# Generated by Django 4.2.3 on 2023-08-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
